/*
 * Pipeline API
 *
 * Pipeline is a feature rich application platform, built for containers on top of Kubernetes to automate the DevOps experience, continuous application development and the lifecycle of deployments. 
 *
 * API version: latest
 * Contact: info@banzaicloud.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipeline
import (
	"time"
)
// ProcessEvent struct for ProcessEvent
type ProcessEvent struct {
	ProcessId string `json:"processId,omitempty"`
	Name string `json:"name,omitempty"`
	Log string `json:"log,omitempty"`
	Timestamp time.Time `json:"timestamp,omitempty"`
}
